paths:
  positive_dataset_path: "data/version2/positive_trans_news.pickle"
  negative_dataset_path: "data/version2/negative_trans_news.pickle"
  output_dir: "checkpoints/version2"
  log_dir: "logs/version2"
  save_dir: "models/version2"
  tokenizer_path: "models/tokenizer"
  pretrain_path: "models/wangchanberta-base-att-spm-uncased"
model:
  context_length: 256
training:
  num_train_epochs: 20
  seed: 12345
  batch_size: 50
  weight_decay: 9.51207e-5
  learning_rate: 4.05813e-5
  balanced: False